apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: galera
spec:
  serviceName: galera
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: mysql-db
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
  template:
    metadata:
      labels:
        app: galera
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - resources:
            limits:
              cpu: 2
          livenessProbe:
            exec:
              command: ["mysqladmin", "-u", "dummy", "ping"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["mysql", "-h", "127.0.0.1", "-u", "dummy", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            timeoutSeconds: 1
          image: us.gcr.io/trillian-test/galera:experimental
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          volumeMounts:
            - name: mysql-db
              mountPath: /var/lib/mysql
          env:
            - name: WSREP_SST_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-username
            - name: WSREP_SST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: sst-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password

