apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # These values must be base64 encoded.
  # They should be changed and kept secret for production deployments.
  sst-username: c3N0
  sst-password: c3N0
  root-password: emFwaG9k
---

